spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aws.connect.psdb.cloud:3306/beta?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: yl7d46itvfsdrf93z2w1
    password: pscale_pw_ljgqBgKBqtNli5UZGElNE79sttQI2Cr38dShliWjc23
#mybatis\u914D\u7F6E
mybatis-plus:
  # MyBaits \u522B\u540D\u5305\u626B\u63CF\u8DEF\u5F84\uFF0C\u901A\u8FC7\u8BE5\u5C5E\u6027\u53EF\u4EE5\u7ED9\u5305\u4E2D\u7684\u7C7B\u6CE8\u518C\u522B\u540D
  type-aliases-package: com.liuhappy.beta.vo
  configuration:
    # \u8FD9\u4E2A\u914D\u7F6E\u4F1A\u5C06\u6267\u884C\u7684sql\u6253\u5370\u51FA\u6765\uFF0C\u5728\u5F00\u53D1\u6216\u6D4B\u8BD5\u7684\u65F6\u5019\u53EF\u4EE5\u7528
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # \u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080

